# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ca51d64d78f57f1c72ea8f636e10df89a8260a8b53f8534b9b3aeb9b7cc63fae8a16d6869ac27ee33aaa121fe35e8616b1880f800f2e2267fb42b22f8befe9

test:
  secret_key_base: 183430f8c0536ef962fd9b162cae2d2333e0bada648df26a02fc0bbd2a6f956675f3c3b88e7eb9c430483d56a9877db6366e95eb60ba555aeb060285358a0f8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
